# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import day16_sensor_pb2 as day16__sensor__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in day16_sensor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SmartFactoryStub(object):
    """1. 定义“服务”：相当于定义一个可以被远程调用的“类”
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportData = channel.unary_unary(
                '/factory.SmartFactory/ReportData',
                request_serializer=day16__sensor__pb2.SensorRequest.SerializeToString,
                response_deserializer=day16__sensor__pb2.SensorResponse.FromString,
                _registered_method=True)


class SmartFactoryServicer(object):
    """1. 定义“服务”：相当于定义一个可以被远程调用的“类”
    """

    def ReportData(self, request, context):
        """定义一个“方法”：上报数据。 
        接收 SensorRequest，返回 SensorResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SmartFactoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportData': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportData,
                    request_deserializer=day16__sensor__pb2.SensorRequest.FromString,
                    response_serializer=day16__sensor__pb2.SensorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'factory.SmartFactory', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('factory.SmartFactory', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SmartFactory(object):
    """1. 定义“服务”：相当于定义一个可以被远程调用的“类”
    """

    @staticmethod
    def ReportData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/factory.SmartFactory/ReportData',
            day16__sensor__pb2.SensorRequest.SerializeToString,
            day16__sensor__pb2.SensorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
