"""empty message

Revision ID: 254bcbd92784
Revises: 0a7aee54f5a1
Create Date: 2026-03-06 23:16:30.845893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '254bcbd92784'
down_revision: Union[str, Sequence[str], None] = '0a7aee54f5a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_chat_content_gin'), table_name='chat_history', postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    op.add_column('perception_tasks', sa.Column('processing_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perception_tasks', 'processing_time')
    op.create_table('agent_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'PENDING'::text"), autoincrement=False, nullable=True),
    sa.Column('worker_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_tasks_pkey'))
    )
    op.create_table('chat_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_history_pkey'))
    )
    op.create_index(op.f('idx_chat_content_gin'), 'chat_history', ['content'], unique=False, postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
