# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8000/openapi.json
#   timestamp: 2026-04-11T00:35:19+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field, constr


class DiagnosticResult(BaseModel):
    is_critical: bool = Field(..., description='是否属于致命故障', title='Is Critical')
    suggestion: str = Field(..., description='AI 给出的维修建议', title='Suggestion')


class DiagnosticTask(BaseModel):
    vin: constr(min_length=17, max_length=17) = Field(
        ..., description='车辆17位唯一识别码', examples=['5YJ3E1EB...'], title='Vin'
    )
    fault_code: str = Field(
        ..., description='传感器捕获的故障码', examples=['BMS_a066'], title='Fault Code'
    )


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')
    input: Any | None = Field(None, title='Input')
    ctx: dict[str, Any] | None = Field(None, title='Context')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')
